apiVersion: v1
kind: Namespace
metadata:
    name: project

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: jenkinscontainer
        image: senthilkumar03/jenkinrepo:1000
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: project
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
